#-------------------------------------------------
#
# Project created by QtCreator 2019-06-17T13:28:47
#
#-------------------------------------------------

QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = exam
TEMPLATE = app

# The following define makes your compiler emit warnings if you use
# any feature of Qt which has been marked as deprecated (the exact warnings
# depend on your compiler). Please consult the documentation of the
# deprecated API in order to know how to port your code away from it.
DEFINES += QT_DEPRECATED_WARNINGS

# You can also make your code fail to compile if you use deprecated APIs.
# In order to do so, uncomment the following line.
# You can also select to disable deprecated APIs only up to a certain version of Qt.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0

CONFIG += c++11

SOURCES += \
        main.cpp \
        mainwindow.cpp \
    code.cpp \
    set.cpp

HEADERS += \
        mainwindow.h \
    dclist.h \
    datastructure.h \
    bplustree.h \
    rbtree.h \
    stllist.h \
    stlvector.h \
    stlmap.h \
    code.h \
    sorting.h \
    dsbridge.h \
    set.h \
    graphviz/bin/exparse.h \
    graphviz/bin/getopt.h \
    graphviz/include/graphviz/arith.h \
    graphviz/include/graphviz/cdt.h \
    graphviz/include/graphviz/cgraph.h \
    graphviz/include/graphviz/color.h \
    graphviz/include/graphviz/geom.h \
    graphviz/include/graphviz/graph.h \
    graphviz/include/graphviz/gvc.h \
    graphviz/include/graphviz/gvcext.h \
    graphviz/include/graphviz/gvcjob.h \
    graphviz/include/graphviz/gvcommon.h \
    graphviz/include/graphviz/gvconfig.h \
    graphviz/include/graphviz/gvplugin.h \
    graphviz/include/graphviz/gvplugin_device.h \
    graphviz/include/graphviz/gvplugin_layout.h \
    graphviz/include/graphviz/gvplugin_loadimage.h \
    graphviz/include/graphviz/gvplugin_render.h \
    graphviz/include/graphviz/gvplugin_textlayout.h \
    graphviz/include/graphviz/gvpr.h \
    graphviz/include/graphviz/pack.h \
    graphviz/include/graphviz/pathgeom.h \
    graphviz/include/graphviz/pathplan.h \
    graphviz/include/graphviz/textpara.h \
    graphviz/include/graphviz/textspan.h \
    graphviz/include/graphviz/types.h \
    graphviz/include/graphviz/usershape.h \
    graphviz/include/graphviz/xdot.h \
    graphviz/release/bin/config.h \
    graphviz/release/bin/exparse.h \
    graphviz/release/bin/getopt.h \
    graphviz/release/include/graphviz/arith.h \
    graphviz/release/include/graphviz/cdt.h \
    graphviz/release/include/graphviz/cgraph.h \
    graphviz/release/include/graphviz/color.h \
    graphviz/release/include/graphviz/geom.h \
    graphviz/release/include/graphviz/graph.h \
    graphviz/release/include/graphviz/gvc.h \
    graphviz/release/include/graphviz/gvcext.h \
    graphviz/release/include/graphviz/gvcjob.h \
    graphviz/release/include/graphviz/gvcommon.h \
    graphviz/release/include/graphviz/gvconfig.h \
    graphviz/release/include/graphviz/gvplugin.h \
    graphviz/release/include/graphviz/gvplugin_device.h \
    graphviz/release/include/graphviz/gvplugin_layout.h \
    graphviz/release/include/graphviz/gvplugin_loadimage.h \
    graphviz/release/include/graphviz/gvplugin_render.h \
    graphviz/release/include/graphviz/gvplugin_textlayout.h \
    graphviz/release/include/graphviz/gvpr.h \
    graphviz/release/include/graphviz/pack.h \
    graphviz/release/include/graphviz/pathgeom.h \
    graphviz/release/include/graphviz/pathplan.h \
    graphviz/release/include/graphviz/textpara.h \
    graphviz/release/include/graphviz/textspan.h \
    graphviz/release/include/graphviz/types.h \
    graphviz/release/include/graphviz/usershape.h \
    graphviz/release/include/graphviz/xdot.h \
    graphviz/release/share/man/man3/cdt.3 \
    graphviz/release/share/man/man3/cgraph.3 \
    graphviz/release/share/man/man3/graph.3 \
    graphviz/release/share/man/man3/gvc.3 \
    graphviz/release/share/man/man3/pathplan.3 \
    graphviz/release/share/man/man3/xdot.3 \
    graphviz/share/man/man3/cdt.3 \
    graphviz/share/man/man3/cgraph.3 \
    graphviz/share/man/man3/graph.3 \
    graphviz/share/man/man3/gvc.3 \
    graphviz/share/man/man3/pathplan.3 \
    graphviz/share/man/man3/xdot.3

FORMS += \
        mainwindow.ui \
    set.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

DISTFILES += \
    stylesheet.qss \
    graphviz/release/share/graphviz/doc/pdf/acyclic.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/bcomps.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/ccomps.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/cdt.3.pdf \
    graphviz/release/share/graphviz/doc/pdf/cgraph.3.pdf \
    graphviz/release/share/graphviz/doc/pdf/circo.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/dijkstra.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/dot.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/dotguide.pdf \
    graphviz/release/share/graphviz/doc/pdf/dotty.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/dottyguide.pdf \
    graphviz/release/share/graphviz/doc/pdf/fdp.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gc.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/graph.3.pdf \
    graphviz/release/share/graphviz/doc/pdf/gv2gxl.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gvc.3.pdf \
    graphviz/release/share/graphviz/doc/pdf/gvcolor.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gvgen.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gvpack.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gvpr.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/gxl2gv.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/lefty.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/leftyguide.pdf \
    graphviz/release/share/graphviz/doc/pdf/libguide.pdf \
    graphviz/release/share/graphviz/doc/pdf/lneato.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/mm2gv.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/neato.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/neatoguide.pdf \
    graphviz/release/share/graphviz/doc/pdf/nop.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/osage.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/pathplan.3.pdf \
    graphviz/release/share/graphviz/doc/pdf/prune.pdf \
    graphviz/release/share/graphviz/doc/pdf/sccmap.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/tred.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/twopi.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/unflatten.1.pdf \
    graphviz/release/share/graphviz/doc/pdf/xdot.3.pdf \
    graphviz/share/graphviz/doc/pdf/acyclic.1.pdf \
    graphviz/share/graphviz/doc/pdf/bcomps.1.pdf \
    graphviz/share/graphviz/doc/pdf/ccomps.1.pdf \
    graphviz/share/graphviz/doc/pdf/cdt.3.pdf \
    graphviz/share/graphviz/doc/pdf/cgraph.3.pdf \
    graphviz/share/graphviz/doc/pdf/circo.1.pdf \
    graphviz/share/graphviz/doc/pdf/dijkstra.1.pdf \
    graphviz/share/graphviz/doc/pdf/dot.1.pdf \
    graphviz/share/graphviz/doc/pdf/dotguide.pdf \
    graphviz/share/graphviz/doc/pdf/dotty.1.pdf \
    graphviz/share/graphviz/doc/pdf/dottyguide.pdf \
    graphviz/share/graphviz/doc/pdf/fdp.1.pdf \
    graphviz/share/graphviz/doc/pdf/gc.1.pdf \
    graphviz/share/graphviz/doc/pdf/graph.3.pdf \
    graphviz/share/graphviz/doc/pdf/gv2gxl.1.pdf \
    graphviz/share/graphviz/doc/pdf/gvc.3.pdf \
    graphviz/share/graphviz/doc/pdf/gvcolor.1.pdf \
    graphviz/share/graphviz/doc/pdf/gvgen.1.pdf \
    graphviz/share/graphviz/doc/pdf/gvpack.1.pdf \
    graphviz/share/graphviz/doc/pdf/gvpr.1.pdf \
    graphviz/share/graphviz/doc/pdf/gxl2gv.1.pdf \
    graphviz/share/graphviz/doc/pdf/lefty.1.pdf \
    graphviz/share/graphviz/doc/pdf/leftyguide.pdf \
    graphviz/share/graphviz/doc/pdf/libguide.pdf \
    graphviz/share/graphviz/doc/pdf/lneato.1.pdf \
    graphviz/share/graphviz/doc/pdf/mm2gv.1.pdf \
    graphviz/share/graphviz/doc/pdf/neato.1.pdf \
    graphviz/share/graphviz/doc/pdf/neatoguide.pdf \
    graphviz/share/graphviz/doc/pdf/nop.1.pdf \
    graphviz/share/graphviz/doc/pdf/osage.1.pdf \
    graphviz/share/graphviz/doc/pdf/pathplan.3.pdf \
    graphviz/share/graphviz/doc/pdf/prune.pdf \
    graphviz/share/graphviz/doc/pdf/sccmap.1.pdf \
    graphviz/share/graphviz/doc/pdf/tred.1.pdf \
    graphviz/share/graphviz/doc/pdf/twopi.1.pdf \
    graphviz/share/graphviz/doc/pdf/unflatten.1.pdf \
    graphviz/share/graphviz/doc/pdf/xdot.3.pdf \
    graphviz/release/share/license.rtf \
    graphviz/share/license.rtf \
    graphviz/release/bin/Temp.rar \
    graphviz/lib/debug/lib/ast.lib \
    graphviz/lib/debug/lib/cdt.lib \
    graphviz/lib/debug/lib/cgraph.lib \
    graphviz/lib/debug/lib/circogen.lib \
    graphviz/lib/debug/lib/dot.lib \
    graphviz/lib/debug/lib/dotgen.lib \
    graphviz/lib/debug/lib/expr.lib \
    graphviz/lib/debug/lib/fdpgen.lib \
    graphviz/lib/debug/lib/gd.lib \
    graphviz/lib/debug/lib/graph.lib \
    graphviz/lib/debug/lib/gts.lib \
    graphviz/lib/debug/lib/gvc.lib \
    graphviz/lib/debug/lib/gvortho.lib \
    graphviz/lib/debug/lib/gvpack.lib \
    graphviz/lib/debug/lib/gvplugin_core.lib \
    graphviz/lib/debug/lib/gvplugin_dot_layout.lib \
    graphviz/lib/debug/lib/gvplugin_gd.lib \
    graphviz/lib/debug/lib/gvplugin_gdiplus.lib \
    graphviz/lib/debug/lib/gvplugin_neato_layout.lib \
    graphviz/lib/debug/lib/gvplugin_pango.lib \
    graphviz/lib/debug/lib/gvprlib.lib \
    graphviz/lib/debug/lib/ingraphs.lib \
    graphviz/lib/debug/lib/minglelib.lib \
    graphviz/lib/debug/lib/neatogen.lib \
    graphviz/lib/debug/lib/osage.lib \
    graphviz/lib/debug/lib/patchwork.lib \
    graphviz/lib/debug/lib/Pathplan.lib \
    graphviz/lib/debug/lib/rbtree.lib \
    graphviz/lib/debug/lib/sfdp.lib \
    graphviz/lib/debug/lib/sfio.lib \
    graphviz/lib/debug/lib/sparse.lib \
    graphviz/lib/debug/lib/topfish.lib \
    graphviz/lib/debug/lib/twopigen.lib \
    graphviz/lib/debug/lib/vmalloc.lib \
    graphviz/lib/debug/lib/vpsc.lib \
    graphviz/lib/debug/lib/xdot.lib \
    graphviz/lib/release/lib/ast.lib \
    graphviz/lib/release/lib/cdt.lib \
    graphviz/lib/release/lib/cgraph.lib \
    graphviz/lib/release/lib/circogen.lib \
    graphviz/lib/release/lib/dot.lib \
    graphviz/lib/release/lib/dotgen.lib \
    graphviz/lib/release/lib/expr.lib \
    graphviz/lib/release/lib/fdpgen.lib \
    graphviz/lib/release/lib/gd.lib \
    graphviz/lib/release/lib/graph.lib \
    graphviz/lib/release/lib/gts.lib \
    graphviz/lib/release/lib/gvc.lib \
    graphviz/lib/release/lib/gvortho.lib \
    graphviz/lib/release/lib/gvpack.lib \
    graphviz/lib/release/lib/gvplugin_core.lib \
    graphviz/lib/release/lib/gvplugin_dot_layout.lib \
    graphviz/lib/release/lib/gvplugin_gd.lib \
    graphviz/lib/release/lib/gvplugin_gdiplus.lib \
    graphviz/lib/release/lib/gvplugin_neato_layout.lib \
    graphviz/lib/release/lib/gvplugin_pango.lib \
    graphviz/lib/release/lib/gvprlib.lib \
    graphviz/lib/release/lib/ingraphs.lib \
    graphviz/lib/release/lib/minglelib.lib \
    graphviz/lib/release/lib/neatogen.lib \
    graphviz/lib/release/lib/osage.lib \
    graphviz/lib/release/lib/patchwork.lib \
    graphviz/lib/release/lib/Pathplan.lib \
    graphviz/lib/release/lib/rbtree.lib \
    graphviz/lib/release/lib/sfdp.lib \
    graphviz/lib/release/lib/sfio.lib \
    graphviz/lib/release/lib/sparse.lib \
    graphviz/lib/release/lib/topfish.lib \
    graphviz/lib/release/lib/twopigen.lib \
    graphviz/lib/release/lib/vmalloc.lib \
    graphviz/lib/release/lib/vpsc.lib \
    graphviz/lib/release/lib/xdot.lib \
    graphviz/release/bin/gts.lib \
    graphviz/release/lib/debug/lib/ast.lib \
    graphviz/release/lib/debug/lib/cdt.lib \
    graphviz/release/lib/debug/lib/cgraph.lib \
    graphviz/release/lib/debug/lib/circogen.lib \
    graphviz/release/lib/debug/lib/dot.lib \
    graphviz/release/lib/debug/lib/dotgen.lib \
    graphviz/release/lib/debug/lib/edgepaintlib.lib \
    graphviz/release/lib/debug/lib/expr.lib \
    graphviz/release/lib/debug/lib/fdpgen.lib \
    graphviz/release/lib/debug/lib/gd.lib \
    graphviz/release/lib/debug/lib/glcomp.lib \
    graphviz/release/lib/debug/lib/graph.lib \
    graphviz/release/lib/debug/lib/gts.lib \
    graphviz/release/lib/debug/lib/gvc.lib \
    graphviz/release/lib/debug/lib/gvmap.lib \
    graphviz/release/lib/debug/lib/gvortho.lib \
    graphviz/release/lib/debug/lib/gvpack.lib \
    graphviz/release/lib/debug/lib/gvplugin_core.lib \
    graphviz/release/lib/debug/lib/gvplugin_dot_layout.lib \
    graphviz/release/lib/debug/lib/gvplugin_gd.lib \
    graphviz/release/lib/debug/lib/gvplugin_gdiplus.lib \
    graphviz/release/lib/debug/lib/gvplugin_neato_layout.lib \
    graphviz/release/lib/debug/lib/gvplugin_pango.lib \
    graphviz/release/lib/debug/lib/gvprlib.lib \
    graphviz/release/lib/debug/lib/ingraphs.lib \
    graphviz/release/lib/debug/lib/ltdl.lib \
    graphviz/release/lib/debug/lib/minglelib.lib \
    graphviz/release/lib/debug/lib/neatogen.lib \
    graphviz/release/lib/debug/lib/osage.lib \
    graphviz/release/lib/debug/lib/patchwork.lib \
    graphviz/release/lib/debug/lib/Pathplan.lib \
    graphviz/release/lib/debug/lib/rbtree.lib \
    graphviz/release/lib/debug/lib/sfdp.lib \
    graphviz/release/lib/debug/lib/sfio.lib \
    graphviz/release/lib/debug/lib/smyrna.lib \
    graphviz/release/lib/debug/lib/sparse.lib \
    graphviz/release/lib/debug/lib/topfish.lib \
    graphviz/release/lib/debug/lib/twopigen.lib \
    graphviz/release/lib/debug/lib/vmalloc.lib \
    graphviz/release/lib/debug/lib/vpsc.lib \
    graphviz/release/lib/debug/lib/xdot.lib \
    graphviz/release/lib/release/lib/ast.lib \
    graphviz/release/lib/release/lib/cdt.lib \
    graphviz/release/lib/release/lib/cgraph.lib \
    graphviz/release/lib/release/lib/circogen.lib \
    graphviz/release/lib/release/lib/dot.lib \
    graphviz/release/lib/release/lib/dotgen.lib \
    graphviz/release/lib/release/lib/edgepaintlib.lib \
    graphviz/release/lib/release/lib/expr.lib \
    graphviz/release/lib/release/lib/fdpgen.lib \
    graphviz/release/lib/release/lib/gd.lib \
    graphviz/release/lib/release/lib/glcomp.lib \
    graphviz/release/lib/release/lib/graph.lib \
    graphviz/release/lib/release/lib/gts.lib \
    graphviz/release/lib/release/lib/gvc.lib \
    graphviz/release/lib/release/lib/gvmap.lib \
    graphviz/release/lib/release/lib/gvortho.lib \
    graphviz/release/lib/release/lib/gvpack.lib \
    graphviz/release/lib/release/lib/gvplugin_core.lib \
    graphviz/release/lib/release/lib/gvplugin_dot_layout.lib \
    graphviz/release/lib/release/lib/gvplugin_gd.lib \
    graphviz/release/lib/release/lib/gvplugin_gdiplus.lib \
    graphviz/release/lib/release/lib/gvplugin_neato_layout.lib \
    graphviz/release/lib/release/lib/gvplugin_pango.lib \
    graphviz/release/lib/release/lib/gvprlib.lib \
    graphviz/release/lib/release/lib/ingraphs.lib \
    graphviz/release/lib/release/lib/ltdl.lib \
    graphviz/release/lib/release/lib/minglelib.lib \
    graphviz/release/lib/release/lib/neatogen.lib \
    graphviz/release/lib/release/lib/osage.lib \
    graphviz/release/lib/release/lib/patchwork.lib \
    graphviz/release/lib/release/lib/Pathplan.lib \
    graphviz/release/lib/release/lib/rbtree.lib \
    graphviz/release/lib/release/lib/sfdp.lib \
    graphviz/release/lib/release/lib/sfio.lib \
    graphviz/release/lib/release/lib/smyrna.lib \
    graphviz/release/lib/release/lib/sparse.lib \
    graphviz/release/lib/release/lib/topfish.lib \
    graphviz/release/lib/release/lib/twopigen.lib \
    graphviz/release/lib/release/lib/vmalloc.lib \
    graphviz/release/lib/release/lib/vpsc.lib \
    graphviz/release/lib/release/lib/xdot.lib \
    graphviz/release/bin/gd.tgz \
    graphviz/release/bin/gts.tgz \
    graphviz/release/share/fonts/FreeSans.ttf \
    graphviz/share/fonts/FreeSans.ttf \
    graphviz/release/share/graphviz/smyrna/smyrna.glade \
    graphviz/share/graphviz/smyrna/smyrna.glade \
    graphviz/bin/acyclic.exe \
    graphviz/bin/ann.dll \
    graphviz/bin/bcomps.exe \
    graphviz/bin/ccomps.exe \
    graphviz/bin/cdt.dll \
    graphviz/bin/cgraph.dll \
    graphviz/bin/circo.exe \
    graphviz/bin/dijkstra.exe \
    graphviz/bin/dot.exe \
    graphviz/bin/dotty.exe \
    graphviz/bin/fc-cache.exe \
    graphviz/bin/fc-cat.exe \
    graphviz/bin/fc-list.exe \
    graphviz/bin/fc-match.exe \
    graphviz/bin/fdp.exe \
    graphviz/bin/fontconfig.dll \
    graphviz/bin/fontconfig_fix.dll \
    graphviz/bin/freetype6.dll \
    graphviz/bin/gc.exe \
    graphviz/bin/glut32.dll \
    graphviz/bin/gml2gv.exe \
    graphviz/bin/graphml2gv.exe \
    graphviz/bin/gv2gml.exe \
    graphviz/bin/gvc.dll \
    graphviz/bin/gvcolor.exe \
    graphviz/bin/gvedit.exe \
    graphviz/bin/gvgen.exe \
    graphviz/bin/gvmap.exe \
    graphviz/bin/gvpack.exe \
    graphviz/bin/gvplugin_core.dll \
    graphviz/bin/gvplugin_dot_layout.dll \
    graphviz/bin/gvplugin_gd.dll \
    graphviz/bin/gvplugin_gdiplus.dll \
    graphviz/bin/gvplugin_neato_layout.dll \
    graphviz/bin/gvplugin_pango.dll \
    graphviz/bin/gvpr.exe \
    graphviz/bin/gxl2gv.exe \
    graphviz/bin/iconv.dll \
    graphviz/bin/intl.dll \
    graphviz/bin/jpeg62.dll \
    graphviz/bin/lefty.exe \
    graphviz/bin/libatk-1.0-0.dll \
    graphviz/bin/libcairo-2.dll \
    graphviz/bin/libexpat-1.dll \
    graphviz/bin/libexpat.dll \
    graphviz/bin/libfontconfig-1.dll \
    graphviz/bin/libfreetype-6.dll \
    graphviz/bin/libgdk-win32-2.0-0.dll \
    graphviz/bin/libgdk_pixbuf-2.0-0.dll \
    graphviz/bin/libgdkglext-win32-1.0-0.dll \
    graphviz/bin/libgio-2.0-0.dll \
    graphviz/bin/libglade-2.0-0.dll \
    graphviz/bin/libglib-2.0-0.dll \
    graphviz/bin/libgmodule-2.0-0.dll \
    graphviz/bin/libgobject-2.0-0.dll \
    graphviz/bin/libgthread-2.0-0.dll \
    graphviz/bin/libgtk-win32-2.0-0.dll \
    graphviz/bin/libgtkglext-win32-1.0-0.dll \
    graphviz/bin/libltdl-3.dll \
    graphviz/bin/libpango-1.0-0.dll \
    graphviz/bin/libpangocairo-1.0-0.dll \
    graphviz/bin/libpangoft2-1.0-0.dll \
    graphviz/bin/libpangowin32-1.0-0.dll \
    graphviz/bin/libpng12.dll \
    graphviz/bin/libpng14-14.dll \
    graphviz/bin/libxml2.dll \
    graphviz/bin/lneato.exe \
    graphviz/bin/ltdl.dll \
    graphviz/bin/mingle.exe \
    graphviz/bin/mm2gv.exe \
    graphviz/bin/neato.exe \
    graphviz/bin/nop.exe \
    graphviz/bin/osage.exe \
    graphviz/bin/patchwork.exe \
    graphviz/bin/Pathplan.dll \
    graphviz/bin/prune.exe \
    graphviz/bin/QtCore4.dll \
    graphviz/bin/QtGui4.dll \
    graphviz/bin/sccmap.exe \
    graphviz/bin/sfdp.exe \
    graphviz/bin/smyrna.exe \
    graphviz/bin/tred.exe \
    graphviz/bin/twopi.exe \
    graphviz/bin/unflatten.exe \
    graphviz/bin/vmalloc.dll \
    graphviz/bin/zlib1.dll \
    graphviz/lib/debug/dll/ann.dll \
    graphviz/lib/debug/dll/cdt.dll \
    graphviz/lib/debug/dll/cgraph.dll \
    graphviz/lib/debug/dll/gvc.dll \
    graphviz/lib/debug/dll/gvplugin_core.dll \
    graphviz/lib/debug/dll/gvplugin_dot_layout.dll \
    graphviz/lib/debug/dll/gvplugin_gd.dll \
    graphviz/lib/debug/dll/gvplugin_gdiplus.dll \
    graphviz/lib/debug/dll/gvplugin_neato_layout.dll \
    graphviz/lib/debug/dll/gvplugin_pango.dll \
    graphviz/lib/debug/dll/Pathplan.dll \
    graphviz/lib/debug/dll/vmalloc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-arabic-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-arabic-lang.dll \
    graphviz/lib/pango/1.6.0/modules/pango-basic-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-basic-win32.dll \
    graphviz/lib/pango/1.6.0/modules/pango-hangul-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-hebrew-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-indic-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-indic-lang.dll \
    graphviz/lib/pango/1.6.0/modules/pango-khmer-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-syriac-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-thai-fc.dll \
    graphviz/lib/pango/1.6.0/modules/pango-tibetan-fc.dll \
    graphviz/lib/release/dll/ann.dll \
    graphviz/lib/release/dll/cdt.dll \
    graphviz/lib/release/dll/cgraph.dll \
    graphviz/lib/release/dll/gvc.dll \
    graphviz/lib/release/dll/gvplugin_core.dll \
    graphviz/lib/release/dll/gvplugin_dot_layout.dll \
    graphviz/lib/release/dll/gvplugin_gd.dll \
    graphviz/lib/release/dll/gvplugin_gdiplus.dll \
    graphviz/lib/release/dll/gvplugin_neato_layout.dll \
    graphviz/lib/release/dll/gvplugin_pango.dll \
    graphviz/lib/release/dll/Pathplan.dll \
    graphviz/lib/release/dll/vmalloc.dll \
    graphviz/release/bin/acyclic.exe \
    graphviz/release/bin/ann.dll \
    graphviz/release/bin/bcomps.exe \
    graphviz/release/bin/ccomps.exe \
    graphviz/release/bin/cdt.dll \
    graphviz/release/bin/cgraph.dll \
    graphviz/release/bin/circo.exe \
    graphviz/release/bin/diffimg.exe \
    graphviz/release/bin/dijkstra.exe \
    graphviz/release/bin/dot.exe \
    graphviz/release/bin/dotty.exe \
    graphviz/release/bin/edgepaint.exe \
    graphviz/release/bin/fc-cache.exe \
    graphviz/release/bin/fc-cat.exe \
    graphviz/release/bin/fc-list.exe \
    graphviz/release/bin/fc-match.exe \
    graphviz/release/bin/fdp.exe \
    graphviz/release/bin/fontconfig.dll \
    graphviz/release/bin/fontconfig_fix.dll \
    graphviz/release/bin/freetype6.dll \
    graphviz/release/bin/gc.exe \
    graphviz/release/bin/glut32.dll \
    graphviz/release/bin/gml2gv.exe \
    graphviz/release/bin/graphml2gv.exe \
    graphviz/release/bin/gv2gml.exe \
    graphviz/release/bin/gvc.dll \
    graphviz/release/bin/gvcolor.exe \
    graphviz/release/bin/gvedit.exe \
    graphviz/release/bin/gvgen.exe \
    graphviz/release/bin/gvmap.exe \
    graphviz/release/bin/gvpack.exe \
    graphviz/release/bin/gvplugin_core.dll \
    graphviz/release/bin/gvplugin_dot_layout.dll \
    graphviz/release/bin/gvplugin_gd.dll \
    graphviz/release/bin/gvplugin_gdiplus.dll \
    graphviz/release/bin/gvplugin_neato_layout.dll \
    graphviz/release/bin/gvplugin_pango.dll \
    graphviz/release/bin/gvpr.exe \
    graphviz/release/bin/gxl2gv.exe \
    graphviz/release/bin/iconv.dll \
    graphviz/release/bin/intl.dll \
    graphviz/release/bin/jpeg62.dll \
    graphviz/release/bin/lefty.exe \
    graphviz/release/bin/libatk-1.0-0.dll \
    graphviz/release/bin/libcairo-2.dll \
    graphviz/release/bin/libexpat-1.dll \
    graphviz/release/bin/libexpat.dll \
    graphviz/release/bin/libfontconfig-1.dll \
    graphviz/release/bin/libfreetype-6.dll \
    graphviz/release/bin/libgdk-win32-2.0-0.dll \
    graphviz/release/bin/libgdk_pixbuf-2.0-0.dll \
    graphviz/release/bin/libgdkglext-win32-1.0-0.dll \
    graphviz/release/bin/libgio-2.0-0.dll \
    graphviz/release/bin/libglade-2.0-0.dll \
    graphviz/release/bin/libglib-2.0-0.dll \
    graphviz/release/bin/libgmodule-2.0-0.dll \
    graphviz/release/bin/libgobject-2.0-0.dll \
    graphviz/release/bin/libgthread-2.0-0.dll \
    graphviz/release/bin/libgtk-win32-2.0-0.dll \
    graphviz/release/bin/libgtkglext-win32-1.0-0.dll \
    graphviz/release/bin/libltdl-3.dll \
    graphviz/release/bin/libpango-1.0-0.dll \
    graphviz/release/bin/libpangocairo-1.0-0.dll \
    graphviz/release/bin/libpangoft2-1.0-0.dll \
    graphviz/release/bin/libpangowin32-1.0-0.dll \
    graphviz/release/bin/libpng12.dll \
    graphviz/release/bin/libpng14-14.dll \
    graphviz/release/bin/librsvg-2-2.dll \
    graphviz/release/bin/libxml2.dll \
    graphviz/release/bin/lneato.exe \
    graphviz/release/bin/ltdl.dll \
    graphviz/release/bin/mingle.exe \
    graphviz/release/bin/mm2gv.exe \
    graphviz/release/bin/neato.exe \
    graphviz/release/bin/nop.exe \
    graphviz/release/bin/osage.exe \
    graphviz/release/bin/patchwork.exe \
    graphviz/release/bin/Pathplan.dll \
    graphviz/release/bin/prune.exe \
    graphviz/release/bin/QtCore4.dll \
    graphviz/release/bin/QtGui4.dll \
    graphviz/release/bin/sccmap.exe \
    graphviz/release/bin/sfdp.exe \
    graphviz/release/bin/smyrna.exe \
    graphviz/release/bin/tred.exe \
    graphviz/release/bin/twopi.exe \
    graphviz/release/bin/unflatten.exe \
    graphviz/release/bin/vmalloc.dll \
    graphviz/release/bin/zlib1.dll \
    graphviz/release/lib/debug/dll/ann.dll \
    graphviz/release/lib/debug/dll/cdt.dll \
    graphviz/release/lib/debug/dll/cgraph.dll \
    graphviz/release/lib/debug/dll/gvc.dll \
    graphviz/release/lib/debug/dll/gvplugin_core.dll \
    graphviz/release/lib/debug/dll/gvplugin_dot_layout.dll \
    graphviz/release/lib/debug/dll/gvplugin_gd.dll \
    graphviz/release/lib/debug/dll/gvplugin_gdiplus.dll \
    graphviz/release/lib/debug/dll/gvplugin_neato_layout.dll \
    graphviz/release/lib/debug/dll/gvplugin_pango.dll \
    graphviz/release/lib/debug/dll/Pathplan.dll \
    graphviz/release/lib/debug/dll/vmalloc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-arabic-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-arabic-lang.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-basic-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-basic-win32.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-hangul-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-hebrew-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-indic-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-indic-lang.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-khmer-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-syriac-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-thai-fc.dll \
    graphviz/release/lib/pango/1.6.0/modules/pango-tibetan-fc.dll \
    graphviz/release/lib/release/dll/ann.dll \
    graphviz/release/lib/release/dll/cdt.dll \
    graphviz/release/lib/release/dll/cgraph.dll \
    graphviz/release/lib/release/dll/gvc.dll \
    graphviz/release/lib/release/dll/gvplugin_core.dll \
    graphviz/release/lib/release/dll/gvplugin_dot_layout.dll \
    graphviz/release/lib/release/dll/gvplugin_gd.dll \
    graphviz/release/lib/release/dll/gvplugin_gdiplus.dll \
    graphviz/release/lib/release/dll/gvplugin_neato_layout.dll \
    graphviz/release/lib/release/dll/gvplugin_pango.dll \
    graphviz/release/lib/release/dll/Pathplan.dll \
    graphviz/release/lib/release/dll/vmalloc.dll \
    graphviz/release/share/graphviz/doc/html/info/Thumbs.db \
    graphviz/release/share/Thumbs.db \
    graphviz/share/graphviz/doc/html/info/Thumbs.db \
    graphviz/share/Thumbs.db \
    graphviz/etc/fonts/conf.avail/10-autohint.conf \
    graphviz/etc/fonts/conf.avail/10-no-sub-pixel.conf \
    graphviz/etc/fonts/conf.avail/10-sub-pixel-bgr.conf \
    graphviz/etc/fonts/conf.avail/10-sub-pixel-rgb.conf \
    graphviz/etc/fonts/conf.avail/10-sub-pixel-vbgr.conf \
    graphviz/etc/fonts/conf.avail/10-sub-pixel-vrgb.conf \
    graphviz/etc/fonts/conf.avail/10-unhinted.conf \
    graphviz/etc/fonts/conf.avail/20-fix-globaladvance.conf \
    graphviz/etc/fonts/conf.avail/20-lohit-gujarati.conf \
    graphviz/etc/fonts/conf.avail/20-unhint-small-vera.conf \
    graphviz/etc/fonts/conf.avail/30-amt-aliases.conf \
    graphviz/etc/fonts/conf.avail/30-urw-aliases.conf \
    graphviz/etc/fonts/conf.avail/40-generic.conf \
    graphviz/etc/fonts/conf.avail/49-sansserif.conf \
    graphviz/etc/fonts/conf.avail/50-user.conf \
    graphviz/etc/fonts/conf.avail/51-local.conf \
    graphviz/etc/fonts/conf.avail/60-latin.conf \
    graphviz/etc/fonts/conf.avail/65-fonts-persian.conf \
    graphviz/etc/fonts/conf.avail/65-nonlatin.conf \
    graphviz/etc/fonts/conf.avail/69-unifont.conf \
    graphviz/etc/fonts/conf.avail/70-no-bitmaps.conf \
    graphviz/etc/fonts/conf.avail/70-yes-bitmaps.conf \
    graphviz/etc/fonts/conf.avail/80-delicious.conf \
    graphviz/etc/fonts/conf.avail/90-synthetic.conf \
    graphviz/etc/fonts/conf.d/20-fix-globaladvance.conf \
    graphviz/etc/fonts/conf.d/20-lohit-gujarati.conf \
    graphviz/etc/fonts/conf.d/20-unhint-small-vera.conf \
    graphviz/etc/fonts/conf.d/30-amt-aliases.conf \
    graphviz/etc/fonts/conf.d/30-urw-aliases.conf \
    graphviz/etc/fonts/conf.d/40-generic.conf \
    graphviz/etc/fonts/conf.d/49-sansserif.conf \
    graphviz/etc/fonts/conf.d/50-user.conf \
    graphviz/etc/fonts/conf.d/51-local.conf \
    graphviz/etc/fonts/conf.d/60-latin.conf \
    graphviz/etc/fonts/conf.d/65-fonts-persian.conf \
    graphviz/etc/fonts/conf.d/65-nonlatin.conf \
    graphviz/etc/fonts/conf.d/69-unifont.conf \
    graphviz/etc/fonts/conf.d/80-delicious.conf \
    graphviz/etc/fonts/conf.d/90-synthetic.conf \
    graphviz/etc/fonts/fonts.conf \
    graphviz/fonts/conf.avail/10-autohint.conf \
    graphviz/fonts/conf.avail/10-no-sub-pixel.conf \
    graphviz/fonts/conf.avail/10-sub-pixel-bgr.conf \
    graphviz/fonts/conf.avail/10-sub-pixel-rgb.conf \
    graphviz/fonts/conf.avail/10-sub-pixel-vbgr.conf \
    graphviz/fonts/conf.avail/10-sub-pixel-vrgb.conf \
    graphviz/fonts/conf.avail/10-unhinted.conf \
    graphviz/fonts/conf.avail/20-fix-globaladvance.conf \
    graphviz/fonts/conf.avail/20-lohit-gujarati.conf \
    graphviz/fonts/conf.avail/20-unhint-small-vera.conf \
    graphviz/fonts/conf.avail/30-amt-aliases.conf \
    graphviz/fonts/conf.avail/30-urw-aliases.conf \
    graphviz/fonts/conf.avail/40-generic.conf \
    graphviz/fonts/conf.avail/49-sansserif.conf \
    graphviz/fonts/conf.avail/50-user.conf \
    graphviz/fonts/conf.avail/51-local.conf \
    graphviz/fonts/conf.avail/60-latin.conf \
    graphviz/fonts/conf.avail/65-fonts-persian.conf \
    graphviz/fonts/conf.avail/65-nonlatin.conf \
    graphviz/fonts/conf.avail/69-unifont.conf \
    graphviz/fonts/conf.avail/70-no-bitmaps.conf \
    graphviz/fonts/conf.avail/70-yes-bitmaps.conf \
    graphviz/fonts/conf.avail/80-delicious.conf \
    graphviz/fonts/conf.avail/90-synthetic.conf \
    graphviz/fonts/conf.d/20-fix-globaladvance.conf \
    graphviz/fonts/conf.d/20-lohit-gujarati.conf \
    graphviz/fonts/conf.d/20-unhint-small-vera.conf \
    graphviz/fonts/conf.d/30-amt-aliases.conf \
    graphviz/fonts/conf.d/30-urw-aliases.conf \
    graphviz/fonts/conf.d/40-generic.conf \
    graphviz/fonts/conf.d/49-sansserif.conf \
    graphviz/fonts/conf.d/50-user.conf \
    graphviz/fonts/conf.d/51-local.conf \
    graphviz/fonts/conf.d/60-latin.conf \
    graphviz/fonts/conf.d/65-fonts-persian.conf \
    graphviz/fonts/conf.d/65-nonlatin.conf \
    graphviz/fonts/conf.d/69-unifont.conf \
    graphviz/fonts/conf.d/80-delicious.conf \
    graphviz/fonts/conf.d/90-synthetic.conf \
    graphviz/fonts/fonts.conf \
    graphviz/release/etc/fonts/conf.avail/10-autohint.conf \
    graphviz/release/etc/fonts/conf.avail/10-no-sub-pixel.conf \
    graphviz/release/etc/fonts/conf.avail/10-sub-pixel-bgr.conf \
    graphviz/release/etc/fonts/conf.avail/10-sub-pixel-rgb.conf \
    graphviz/release/etc/fonts/conf.avail/10-sub-pixel-vbgr.conf \
    graphviz/release/etc/fonts/conf.avail/10-sub-pixel-vrgb.conf \
    graphviz/release/etc/fonts/conf.avail/10-unhinted.conf \
    graphviz/release/etc/fonts/conf.avail/20-fix-globaladvance.conf \
    graphviz/release/etc/fonts/conf.avail/20-lohit-gujarati.conf \
    graphviz/release/etc/fonts/conf.avail/20-unhint-small-vera.conf \
    graphviz/release/etc/fonts/conf.avail/30-amt-aliases.conf \
    graphviz/release/etc/fonts/conf.avail/30-urw-aliases.conf \
    graphviz/release/etc/fonts/conf.avail/40-generic.conf \
    graphviz/release/etc/fonts/conf.avail/49-sansserif.conf \
    graphviz/release/etc/fonts/conf.avail/50-user.conf \
    graphviz/release/etc/fonts/conf.avail/51-local.conf \
    graphviz/release/etc/fonts/conf.avail/60-latin.conf \
    graphviz/release/etc/fonts/conf.avail/65-fonts-persian.conf \
    graphviz/release/etc/fonts/conf.avail/65-nonlatin.conf \
    graphviz/release/etc/fonts/conf.avail/69-unifont.conf \
    graphviz/release/etc/fonts/conf.avail/70-no-bitmaps.conf \
    graphviz/release/etc/fonts/conf.avail/70-yes-bitmaps.conf \
    graphviz/release/etc/fonts/conf.avail/80-delicious.conf \
    graphviz/release/etc/fonts/conf.avail/90-synthetic.conf \
    graphviz/release/etc/fonts/conf.d/20-fix-globaladvance.conf \
    graphviz/release/etc/fonts/conf.d/20-lohit-gujarati.conf \
    graphviz/release/etc/fonts/conf.d/20-unhint-small-vera.conf \
    graphviz/release/etc/fonts/conf.d/30-amt-aliases.conf \
    graphviz/release/etc/fonts/conf.d/30-urw-aliases.conf \
    graphviz/release/etc/fonts/conf.d/40-generic.conf \
    graphviz/release/etc/fonts/conf.d/49-sansserif.conf \
    graphviz/release/etc/fonts/conf.d/50-user.conf \
    graphviz/release/etc/fonts/conf.d/51-local.conf \
    graphviz/release/etc/fonts/conf.d/60-latin.conf \
    graphviz/release/etc/fonts/conf.d/65-fonts-persian.conf \
    graphviz/release/etc/fonts/conf.d/65-nonlatin.conf \
    graphviz/release/etc/fonts/conf.d/69-unifont.conf \
    graphviz/release/etc/fonts/conf.d/80-delicious.conf \
    graphviz/release/etc/fonts/conf.d/90-synthetic.conf \
    graphviz/release/etc/fonts/fonts.conf \
    graphviz/release/fonts/conf.avail/10-autohint.conf \
    graphviz/release/fonts/conf.avail/10-no-sub-pixel.conf \
    graphviz/release/fonts/conf.avail/10-sub-pixel-bgr.conf \
    graphviz/release/fonts/conf.avail/10-sub-pixel-rgb.conf \
    graphviz/release/fonts/conf.avail/10-sub-pixel-vbgr.conf \
    graphviz/release/fonts/conf.avail/10-sub-pixel-vrgb.conf \
    graphviz/release/fonts/conf.avail/10-unhinted.conf \
    graphviz/release/fonts/conf.avail/20-fix-globaladvance.conf \
    graphviz/release/fonts/conf.avail/20-lohit-gujarati.conf \
    graphviz/release/fonts/conf.avail/20-unhint-small-vera.conf \
    graphviz/release/fonts/conf.avail/30-amt-aliases.conf \
    graphviz/release/fonts/conf.avail/30-urw-aliases.conf \
    graphviz/release/fonts/conf.avail/40-generic.conf \
    graphviz/release/fonts/conf.avail/49-sansserif.conf \
    graphviz/release/fonts/conf.avail/50-user.conf \
    graphviz/release/fonts/conf.avail/51-local.conf \
    graphviz/release/fonts/conf.avail/60-latin.conf \
    graphviz/release/fonts/conf.avail/65-fonts-persian.conf \
    graphviz/release/fonts/conf.avail/65-nonlatin.conf \
    graphviz/release/fonts/conf.avail/69-unifont.conf \
    graphviz/release/fonts/conf.avail/70-no-bitmaps.conf \
    graphviz/release/fonts/conf.avail/70-yes-bitmaps.conf \
    graphviz/release/fonts/conf.avail/80-delicious.conf \
    graphviz/release/fonts/conf.avail/90-synthetic.conf \
    graphviz/release/fonts/conf.d/20-fix-globaladvance.conf \
    graphviz/release/fonts/conf.d/20-lohit-gujarati.conf \
    graphviz/release/fonts/conf.d/20-unhint-small-vera.conf \
    graphviz/release/fonts/conf.d/30-amt-aliases.conf \
    graphviz/release/fonts/conf.d/30-urw-aliases.conf \
    graphviz/release/fonts/conf.d/40-generic.conf \
    graphviz/release/fonts/conf.d/49-sansserif.conf \
    graphviz/release/fonts/conf.d/50-user.conf \
    graphviz/release/fonts/conf.d/51-local.conf \
    graphviz/release/fonts/conf.d/60-latin.conf \
    graphviz/release/fonts/conf.d/65-fonts-persian.conf \
    graphviz/release/fonts/conf.d/65-nonlatin.conf \
    graphviz/release/fonts/conf.d/69-unifont.conf \
    graphviz/release/fonts/conf.d/80-delicious.conf \
    graphviz/release/fonts/conf.d/90-synthetic.conf \
    graphviz/release/fonts/fonts.conf \
    graphviz/release/share/graphviz/doc/html/schema/arguments.xml \
    graphviz/release/share/graphviz/doc/html/schema/attributes.xml \
    graphviz/share/graphviz/doc/html/schema/arguments.xml \
    graphviz/share/graphviz/doc/html/schema/attributes.xml \
    graphviz/etc/fonts/fonts.dtd \
    graphviz/fonts/fonts.dtd \
    graphviz/release/etc/fonts/fonts.dtd \
    graphviz/release/fonts/fonts.dtd \
    graphviz/release/share/graphviz/doc/html/schema/attributes.xslt \
    graphviz/share/graphviz/doc/html/schema/attributes.xslt \
    graphviz/release/bin/gd.zip \
    graphviz/release/share/setuplogo.bmp \
    graphviz/share/setuplogo.bmp \
    graphviz/release/share/graphviz/doc/html/info/a_box.gif \
    graphviz/release/share/graphviz/doc/html/info/a_crow.gif \
    graphviz/release/share/graphviz/doc/html/info/a_diamond.gif \
    graphviz/release/share/graphviz/doc/html/info/a_dot.gif \
    graphviz/release/share/graphviz/doc/html/info/a_ediamond.gif \
    graphviz/release/share/graphviz/doc/html/info/a_empty.gif \
    graphviz/release/share/graphviz/doc/html/info/a_forward.gif \
    graphviz/release/share/graphviz/doc/html/info/a_halfopen.gif \
    graphviz/release/share/graphviz/doc/html/info/a_inv.gif \
    graphviz/release/share/graphviz/doc/html/info/a_invdot.gif \
    graphviz/release/share/graphviz/doc/html/info/a_invempty.gif \
    graphviz/release/share/graphviz/doc/html/info/a_invodot.gif \
    graphviz/release/share/graphviz/doc/html/info/a_lteeoldiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/a_nohead.gif \
    graphviz/release/share/graphviz/doc/html/info/a_none.gif \
    graphviz/release/share/graphviz/doc/html/info/a_normal.gif \
    graphviz/release/share/graphviz/doc/html/info/a_obox.gif \
    graphviz/release/share/graphviz/doc/html/info/a_odiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/a_odot.gif \
    graphviz/release/share/graphviz/doc/html/info/a_open.gif \
    graphviz/release/share/graphviz/doc/html/info/a_tee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_box.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_crow.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_diamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_dot.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_inv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_lbox.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_lcrow.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_ldiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_linv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_lnormal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_ltee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_lvee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_none.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_normal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_obox.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_odiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_odot.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_oinv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_olbox.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_oldiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_olinv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_olnormal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_onormal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_orbox.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_ordiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_orinv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_ornormal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rbox.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rcrow.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rdiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rinv.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rnormal.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rtee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_rvee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_tee.gif \
    graphviz/release/share/graphviz/doc/html/info/aa_vee.gif \
    graphviz/release/share/graphviz/doc/html/info/back.gif \
    graphviz/release/share/graphviz/doc/html/info/both.gif \
    graphviz/release/share/graphviz/doc/html/info/box.gif \
    graphviz/release/share/graphviz/doc/html/info/box3d.gif \
    graphviz/release/share/graphviz/doc/html/info/circle.gif \
    graphviz/release/share/graphviz/doc/html/info/colorlist.gif \
    graphviz/release/share/graphviz/doc/html/info/component.gif \
    graphviz/release/share/graphviz/doc/html/info/constraint.gif \
    graphviz/release/share/graphviz/doc/html/info/diamond.gif \
    graphviz/release/share/graphviz/doc/html/info/doublecircle.gif \
    graphviz/release/share/graphviz/doc/html/info/doubleoctagon.gif \
    graphviz/release/share/graphviz/doc/html/info/egg.gif \
    graphviz/release/share/graphviz/doc/html/info/ellipse.gif \
    graphviz/release/share/graphviz/doc/html/info/fill.gif \
    graphviz/release/share/graphviz/doc/html/info/folder.gif \
    graphviz/release/share/graphviz/doc/html/info/forward.gif \
    graphviz/release/share/graphviz/doc/html/info/hexagon.gif \
    graphviz/release/share/graphviz/doc/html/info/house.gif \
    graphviz/release/share/graphviz/doc/html/info/html1.gif \
    graphviz/release/share/graphviz/doc/html/info/html2.gif \
    graphviz/release/share/graphviz/doc/html/info/html3.gif \
    graphviz/release/share/graphviz/doc/html/info/html4.gif \
    graphviz/release/share/graphviz/doc/html/info/invhouse.gif \
    graphviz/release/share/graphviz/doc/html/info/invtrapezium.gif \
    graphviz/release/share/graphviz/doc/html/info/invtriangle.gif \
    graphviz/release/share/graphviz/doc/html/info/Mcircle.gif \
    graphviz/release/share/graphviz/doc/html/info/Mdiamond.gif \
    graphviz/release/share/graphviz/doc/html/info/mrecord.gif \
    graphviz/release/share/graphviz/doc/html/info/Msquare.gif \
    graphviz/release/share/graphviz/doc/html/info/nohead.gif \
    graphviz/release/share/graphviz/doc/html/info/none.gif \
    graphviz/release/share/graphviz/doc/html/info/note.gif \
    graphviz/release/share/graphviz/doc/html/info/octagon.gif \
    graphviz/release/share/graphviz/doc/html/info/parallelogram.gif \
    graphviz/release/share/graphviz/doc/html/info/pentagon.gif \
    graphviz/release/share/graphviz/doc/html/info/plaintext.gif \
    graphviz/release/share/graphviz/doc/html/info/point.gif \
    graphviz/release/share/graphviz/doc/html/info/polygon.gif \
    graphviz/release/share/graphviz/doc/html/info/record.gif \
    graphviz/release/share/graphviz/doc/html/info/record2.gif \
    graphviz/release/share/graphviz/doc/html/info/rect.gif \
    graphviz/release/share/graphviz/doc/html/info/rectangle.gif \
    graphviz/release/share/graphviz/doc/html/info/round.gif \
    graphviz/release/share/graphviz/doc/html/info/septagon.gif \
    graphviz/release/share/graphviz/doc/html/info/tab.gif \
    graphviz/release/share/graphviz/doc/html/info/trapezium.gif \
    graphviz/release/share/graphviz/doc/html/info/triangle.gif \
    graphviz/release/share/graphviz/doc/html/info/tripleoctagon.gif \
    graphviz/release/share/graphviz/graphs/directed/arrows.gif \
    graphviz/release/share/graphviz/graphs/directed/awilliams.gif \
    graphviz/release/share/graphviz/graphs/directed/clust3.gif \
    graphviz/release/share/graphviz/graphs/directed/jcctree.gif \
    graphviz/release/share/graphviz/graphs/directed/jsort.gif \
    graphviz/release/share/graphviz/graphs/directed/oldarrows.gif \
    graphviz/release/share/graphviz/graphs/directed/polypoly.gif \
    graphviz/release/share/graphviz/graphs/directed/world.gif \
    graphviz/share/graphviz/doc/html/info/a_box.gif \
    graphviz/share/graphviz/doc/html/info/a_crow.gif \
    graphviz/share/graphviz/doc/html/info/a_diamond.gif \
    graphviz/share/graphviz/doc/html/info/a_dot.gif \
    graphviz/share/graphviz/doc/html/info/a_ediamond.gif \
    graphviz/share/graphviz/doc/html/info/a_empty.gif \
    graphviz/share/graphviz/doc/html/info/a_forward.gif \
    graphviz/share/graphviz/doc/html/info/a_halfopen.gif \
    graphviz/share/graphviz/doc/html/info/a_inv.gif \
    graphviz/share/graphviz/doc/html/info/a_invdot.gif \
    graphviz/share/graphviz/doc/html/info/a_invempty.gif \
    graphviz/share/graphviz/doc/html/info/a_invodot.gif \
    graphviz/share/graphviz/doc/html/info/a_lteeoldiamond.gif \
    graphviz/share/graphviz/doc/html/info/a_nohead.gif \
    graphviz/share/graphviz/doc/html/info/a_none.gif \
    graphviz/share/graphviz/doc/html/info/a_normal.gif \
    graphviz/share/graphviz/doc/html/info/a_obox.gif \
    graphviz/share/graphviz/doc/html/info/a_odiamond.gif \
    graphviz/share/graphviz/doc/html/info/a_odot.gif \
    graphviz/share/graphviz/doc/html/info/a_open.gif \
    graphviz/share/graphviz/doc/html/info/a_tee.gif \
    graphviz/share/graphviz/doc/html/info/aa_box.gif \
    graphviz/share/graphviz/doc/html/info/aa_crow.gif \
    graphviz/share/graphviz/doc/html/info/aa_diamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_dot.gif \
    graphviz/share/graphviz/doc/html/info/aa_inv.gif \
    graphviz/share/graphviz/doc/html/info/aa_lbox.gif \
    graphviz/share/graphviz/doc/html/info/aa_lcrow.gif \
    graphviz/share/graphviz/doc/html/info/aa_ldiamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_linv.gif \
    graphviz/share/graphviz/doc/html/info/aa_lnormal.gif \
    graphviz/share/graphviz/doc/html/info/aa_ltee.gif \
    graphviz/share/graphviz/doc/html/info/aa_lvee.gif \
    graphviz/share/graphviz/doc/html/info/aa_none.gif \
    graphviz/share/graphviz/doc/html/info/aa_normal.gif \
    graphviz/share/graphviz/doc/html/info/aa_obox.gif \
    graphviz/share/graphviz/doc/html/info/aa_odiamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_odot.gif \
    graphviz/share/graphviz/doc/html/info/aa_oinv.gif \
    graphviz/share/graphviz/doc/html/info/aa_olbox.gif \
    graphviz/share/graphviz/doc/html/info/aa_oldiamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_olinv.gif \
    graphviz/share/graphviz/doc/html/info/aa_olnormal.gif \
    graphviz/share/graphviz/doc/html/info/aa_onormal.gif \
    graphviz/share/graphviz/doc/html/info/aa_orbox.gif \
    graphviz/share/graphviz/doc/html/info/aa_ordiamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_orinv.gif \
    graphviz/share/graphviz/doc/html/info/aa_ornormal.gif \
    graphviz/share/graphviz/doc/html/info/aa_rbox.gif \
    graphviz/share/graphviz/doc/html/info/aa_rcrow.gif \
    graphviz/share/graphviz/doc/html/info/aa_rdiamond.gif \
    graphviz/share/graphviz/doc/html/info/aa_rinv.gif \
    graphviz/share/graphviz/doc/html/info/aa_rnormal.gif \
    graphviz/share/graphviz/doc/html/info/aa_rtee.gif \
    graphviz/share/graphviz/doc/html/info/aa_rvee.gif \
    graphviz/share/graphviz/doc/html/info/aa_tee.gif \
    graphviz/share/graphviz/doc/html/info/aa_vee.gif \
    graphviz/share/graphviz/doc/html/info/back.gif \
    graphviz/share/graphviz/doc/html/info/both.gif \
    graphviz/share/graphviz/doc/html/info/box.gif \
    graphviz/share/graphviz/doc/html/info/box3d.gif \
    graphviz/share/graphviz/doc/html/info/circle.gif \
    graphviz/share/graphviz/doc/html/info/colorlist.gif \
    graphviz/share/graphviz/doc/html/info/component.gif \
    graphviz/share/graphviz/doc/html/info/constraint.gif \
    graphviz/share/graphviz/doc/html/info/diamond.gif \
    graphviz/share/graphviz/doc/html/info/doublecircle.gif \
    graphviz/share/graphviz/doc/html/info/doubleoctagon.gif \
    graphviz/share/graphviz/doc/html/info/egg.gif \
    graphviz/share/graphviz/doc/html/info/ellipse.gif \
    graphviz/share/graphviz/doc/html/info/fill.gif \
    graphviz/share/graphviz/doc/html/info/folder.gif \
    graphviz/share/graphviz/doc/html/info/forward.gif \
    graphviz/share/graphviz/doc/html/info/hexagon.gif \
    graphviz/share/graphviz/doc/html/info/house.gif \
    graphviz/share/graphviz/doc/html/info/html1.gif \
    graphviz/share/graphviz/doc/html/info/html2.gif \
    graphviz/share/graphviz/doc/html/info/html3.gif \
    graphviz/share/graphviz/doc/html/info/html4.gif \
    graphviz/share/graphviz/doc/html/info/invhouse.gif \
    graphviz/share/graphviz/doc/html/info/invtrapezium.gif \
    graphviz/share/graphviz/doc/html/info/invtriangle.gif \
    graphviz/share/graphviz/doc/html/info/Mcircle.gif \
    graphviz/share/graphviz/doc/html/info/Mdiamond.gif \
    graphviz/share/graphviz/doc/html/info/mrecord.gif \
    graphviz/share/graphviz/doc/html/info/Msquare.gif \
    graphviz/share/graphviz/doc/html/info/nohead.gif \
    graphviz/share/graphviz/doc/html/info/none.gif \
    graphviz/share/graphviz/doc/html/info/note.gif \
    graphviz/share/graphviz/doc/html/info/octagon.gif \
    graphviz/share/graphviz/doc/html/info/parallelogram.gif \
    graphviz/share/graphviz/doc/html/info/pentagon.gif \
    graphviz/share/graphviz/doc/html/info/plaintext.gif \
    graphviz/share/graphviz/doc/html/info/point.gif \
    graphviz/share/graphviz/doc/html/info/polygon.gif \
    graphviz/share/graphviz/doc/html/info/record.gif \
    graphviz/share/graphviz/doc/html/info/record2.gif \
    graphviz/share/graphviz/doc/html/info/rect.gif \
    graphviz/share/graphviz/doc/html/info/rectangle.gif \
    graphviz/share/graphviz/doc/html/info/round.gif \
    graphviz/share/graphviz/doc/html/info/septagon.gif \
    graphviz/share/graphviz/doc/html/info/tab.gif \
    graphviz/share/graphviz/doc/html/info/trapezium.gif \
    graphviz/share/graphviz/doc/html/info/triangle.gif \
    graphviz/share/graphviz/doc/html/info/tripleoctagon.gif \
    graphviz/share/graphviz/graphs/directed/arrows.gif \
    graphviz/share/graphviz/graphs/directed/awilliams.gif \
    graphviz/share/graphviz/graphs/directed/clust3.gif \
    graphviz/share/graphviz/graphs/directed/jcctree.gif \
    graphviz/share/graphviz/graphs/directed/jsort.gif \
    graphviz/share/graphviz/graphs/directed/oldarrows.gif \
    graphviz/share/graphviz/graphs/directed/polypoly.gif \
    graphviz/share/graphviz/graphs/directed/world.gif \
    graphviz/release/share/graphviz/graphs/directed/records.jpg \
    graphviz/release/share/graphviz/graphs/directed/russian.jpg \
    graphviz/release/share/graphviz/graphs/directed/triedds.jpg \
    graphviz/release/share/graphviz/graphs/directed/viewfile.jpg \
    graphviz/share/graphviz/graphs/directed/records.jpg \
    graphviz/share/graphviz/graphs/directed/russian.jpg \
    graphviz/share/graphviz/graphs/directed/triedds.jpg \
    graphviz/share/graphviz/graphs/directed/viewfile.jpg \
    graphviz/release/share/graphviz/doc/html/info/plugins.png \
    graphviz/release/share/graphviz/doc/html/info/sdlshapes.png \
    graphviz/release/share/graphviz/doc/html/Gdtclft2.2.5.example.png \
    graphviz/release/share/graphviz/doc/html/pspdf.png \
    graphviz/release/share/graphviz/graphs/directed/records.png \
    graphviz/release/share/graphviz/smyrna/2D.png \
    graphviz/release/share/graphviz/smyrna/3D.png \
    graphviz/release/share/graphviz/smyrna/add_edge.png \
    graphviz/release/share/graphviz/smyrna/AntiselectRect.png \
    graphviz/release/share/graphviz/smyrna/AntiselectRectX.png \
    graphviz/release/share/graphviz/smyrna/center.png \
    graphviz/release/share/graphviz/smyrna/cursor.png \
    graphviz/release/share/graphviz/smyrna/deletE_edge.png \
    graphviz/release/share/graphviz/smyrna/delete_node.png \
    graphviz/release/share/graphviz/smyrna/details.png \
    graphviz/release/share/graphviz/smyrna/dot.PNG \
    graphviz/release/share/graphviz/smyrna/edge.png \
    graphviz/release/share/graphviz/smyrna/find_edge.png \
    graphviz/release/share/graphviz/smyrna/find_node.png \
    graphviz/release/share/graphviz/smyrna/fish.PNG \
    graphviz/release/share/graphviz/smyrna/fisheye.png \
    graphviz/release/share/graphviz/smyrna/fit.png \
    graphviz/release/share/graphviz/smyrna/fit_to_screen.png \
    graphviz/release/share/graphviz/smyrna/glade-3.png \
    graphviz/release/share/graphviz/smyrna/hourglass.png \
    graphviz/release/share/graphviz/smyrna/lcirco.png \
    graphviz/release/share/graphviz/smyrna/ldot.png \
    graphviz/release/share/graphviz/smyrna/lfdp.png \
    graphviz/release/share/graphviz/smyrna/lneato.png \
    graphviz/release/share/graphviz/smyrna/ltwopi.png \
    graphviz/release/share/graphviz/smyrna/magifier_zoom_out.png \
    graphviz/release/share/graphviz/smyrna/magnifier.png \
    graphviz/release/share/graphviz/smyrna/magnifier_zoom_in.png \
    graphviz/release/share/graphviz/smyrna/mod_3D.png \
    graphviz/release/share/graphviz/smyrna/mod_fisheye.png \
    graphviz/release/share/graphviz/smyrna/move.png \
    graphviz/release/share/graphviz/smyrna/new_delete.png \
    graphviz/release/share/graphviz/smyrna/new_node.png \
    graphviz/release/share/graphviz/smyrna/newzoom.png \
    graphviz/release/share/graphviz/smyrna/no_fisheye.png \
    graphviz/release/share/graphviz/smyrna/node.png \
    graphviz/release/share/graphviz/smyrna/pan.png \
    graphviz/release/share/graphviz/smyrna/preview.png \
    graphviz/release/share/graphviz/smyrna/rect_select.png \
    graphviz/release/share/graphviz/smyrna/rect_select2.png \
    graphviz/release/share/graphviz/smyrna/rotate.png \
    graphviz/release/share/graphviz/smyrna/select.png \
    graphviz/release/share/graphviz/smyrna/selectr.png \
    graphviz/release/share/graphviz/smyrna/selectx.png \
    graphviz/release/share/graphviz/smyrna/single_select.png \
    graphviz/release/share/graphviz/smyrna/zoom.png \
    graphviz/release/share/graphviz/smyrna/zoom_in.png \
    graphviz/release/share/graphviz/smyrna/zoom_out.png \
    graphviz/release/share/graphviz/smyrna/zoomin.png \
    graphviz/release/share/graphviz/smyrna/zoomout.png \
    graphviz/share/graphviz/doc/html/info/plugins.png \
    graphviz/share/graphviz/doc/html/info/sdlshapes.png \
    graphviz/share/graphviz/doc/html/Gdtclft2.2.5.example.png \
    graphviz/share/graphviz/doc/html/pspdf.png \
    graphviz/share/graphviz/graphs/directed/records.png \
    graphviz/share/graphviz/smyrna/2D.png \
    graphviz/share/graphviz/smyrna/3D.png \
    graphviz/share/graphviz/smyrna/center.png \
    graphviz/share/graphviz/smyrna/details.png \
    graphviz/share/graphviz/smyrna/edge.png \
    graphviz/share/graphviz/smyrna/fish.PNG \
    graphviz/share/graphviz/smyrna/fisheye.png \
    graphviz/share/graphviz/smyrna/fit.png \
    graphviz/share/graphviz/smyrna/magnifier.png \
    graphviz/share/graphviz/smyrna/mod_3D.png \
    graphviz/share/graphviz/smyrna/mod_fisheye.png \
    graphviz/share/graphviz/smyrna/move.png \
    graphviz/share/graphviz/smyrna/no_fisheye.png \
    graphviz/share/graphviz/smyrna/node.png \
    graphviz/share/graphviz/smyrna/pan.png \
    graphviz/share/graphviz/smyrna/preview.png \
    graphviz/share/graphviz/smyrna/rect_select.png \
    graphviz/share/graphviz/smyrna/rect_select2.png \
    graphviz/share/graphviz/smyrna/rotate.png \
    graphviz/share/graphviz/smyrna/zoom.png \
    graphviz/share/graphviz/smyrna/zoomin.png \
    graphviz/share/graphviz/smyrna/zoomout.png \
    graphviz/release/share/graphviz/smyrna/fisheye.raw \
    graphviz/release/share/graphviz/smyrna/ok.raw \
    graphviz/release/share/graphviz/smyrna/ok2.raw \
    graphviz/release/share/graphviz/smyrna/ok3.raw \
    graphviz/release/share/graphviz/smyrna/pan.raw \
    graphviz/release/share/graphviz/smyrna/rotate.raw \
    graphviz/release/share/graphviz/smyrna/zoom.raw \
    graphviz/release/share/graphviz/smyrna/zoomminus.raw \
    graphviz/release/share/graphviz/smyrna/zoomplus.raw \
    graphviz/release/share/graphviz/smyrna/arial.tga \
    graphviz/bin/GVedit.html \
    graphviz/release/bin/GVedit.html \
    graphviz/release/share/graphviz/doc/html/info/arrows.html \
    graphviz/release/share/graphviz/doc/html/info/attrs.html \
    graphviz/release/share/graphviz/doc/html/info/colors.html \
    graphviz/release/share/graphviz/doc/html/info/command.html \
    graphviz/release/share/graphviz/doc/html/info/grammar.html \
    graphviz/release/share/graphviz/doc/html/info/index.html \
    graphviz/release/share/graphviz/doc/html/info/lang.html \
    graphviz/release/share/graphviz/doc/html/info/output.html \
    graphviz/release/share/graphviz/doc/html/info/shapes.html \
    graphviz/release/share/graphviz/doc/html/build.html \
    graphviz/release/share/graphviz/doc/html/char.html \
    graphviz/release/share/graphviz/doc/html/FAQ.html \
    graphviz/release/share/graphviz/doc/html/gd.html \
    graphviz/release/share/graphviz/doc/html/GVedit.html \
    graphviz/release/share/graphviz/doc/html/index.html \
    graphviz/release/share/graphviz/doc/html/todo.html \
    graphviz/release/share/graphviz/doc/html/winbuild.html \
    graphviz/share/graphviz/doc/html/info/arrows.html \
    graphviz/share/graphviz/doc/html/info/attrs.html \
    graphviz/share/graphviz/doc/html/info/colors.html \
    graphviz/share/graphviz/doc/html/info/command.html \
    graphviz/share/graphviz/doc/html/info/grammar.html \
    graphviz/share/graphviz/doc/html/info/index.html \
    graphviz/share/graphviz/doc/html/info/lang.html \
    graphviz/share/graphviz/doc/html/info/output.html \
    graphviz/share/graphviz/doc/html/info/shapes.html \
    graphviz/share/graphviz/doc/html/build.html \
    graphviz/share/graphviz/doc/html/char.html \
    graphviz/share/graphviz/doc/html/FAQ.html \
    graphviz/share/graphviz/doc/html/gd.html \
    graphviz/share/graphviz/doc/html/GVedit.html \
    graphviz/share/graphviz/doc/html/index.html \
    graphviz/share/graphviz/doc/html/todo.html \
    graphviz/share/graphviz/doc/html/winbuild.html \
    graphviz/bin/config6 \
    graphviz/bin/Graphviz.ini \
    graphviz/bin/New Text Document.txt \
    graphviz/bin/props.txt \
    graphviz/bin/Settings.ini \
    graphviz/etc/gtk-2.0/gdk-pixbuf.loaders \
    graphviz/etc/gtk-2.0/gtk.immodules \
    graphviz/etc/gtk-2.0/gtkrc \
    graphviz/gtk-2.0/gdk-pixbuf.loaders \
    graphviz/gtk-2.0/gtk.immodules \
    graphviz/gtk-2.0/gtkrc \
    graphviz/lib/debug/dll/dummyfile.txt \
    graphviz/lib/debug/lib/dummyfile.txt \
    graphviz/lib/lefty/box.lefty \
    graphviz/lib/lefty/def.lefty \
    graphviz/lib/lefty/dotty.lefty \
    graphviz/lib/lefty/dotty_draw.lefty \
    graphviz/lib/lefty/dotty_edit.lefty \
    graphviz/lib/lefty/dotty_layout.lefty \
    graphviz/lib/lefty/dotty_ui.lefty \
    graphviz/lib/lefty/fractal.lefty \
    graphviz/lib/lefty/fractal2.lefty \
    graphviz/lib/lefty/lefty.psp \
    graphviz/lib/lefty/slides.lefty \
    graphviz/lib/lefty/tree.lefty \
    graphviz/lib/pkgconfig/libcdt.pc \
    graphviz/lib/pkgconfig/libcgraph.pc \
    graphviz/lib/pkgconfig/libgraph.pc \
    graphviz/lib/pkgconfig/libgvc.pc \
    graphviz/lib/pkgconfig/libpathplan.pc \
    graphviz/lib/release/dll/dummyfile.txt \
    graphviz/lib/release/lib/dummyfile.txt \
    graphviz/pango/pango.aliases \
    graphviz/pango/pango.modules \
    graphviz/release/bin/config6 \
    graphviz/release/bin/Graphviz.ini \
    graphviz/release/bin/New Text Document.txt \
    graphviz/release/bin/props.txt \
    graphviz/release/bin/Settings.ini \
    graphviz/release/etc/gtk-2.0/gdk-pixbuf.loaders \
    graphviz/release/etc/gtk-2.0/gtk.immodules \
    graphviz/release/etc/gtk-2.0/gtkrc \
    graphviz/release/gtk-2.0/gdk-pixbuf.loaders \
    graphviz/release/gtk-2.0/gtk.immodules \
    graphviz/release/gtk-2.0/gtkrc \
    graphviz/release/lib/debug/dll/dummyfile.txt \
    graphviz/release/lib/debug/lib/dummyfile.txt \
    graphviz/release/lib/lefty/box.lefty \
    graphviz/release/lib/lefty/def.lefty \
    graphviz/release/lib/lefty/dotty.lefty \
    graphviz/release/lib/lefty/dotty_draw.lefty \
    graphviz/release/lib/lefty/dotty_edit.lefty \
    graphviz/release/lib/lefty/dotty_layout.lefty \
    graphviz/release/lib/lefty/dotty_ui.lefty \
    graphviz/release/lib/lefty/fractal.lefty \
    graphviz/release/lib/lefty/fractal2.lefty \
    graphviz/release/lib/lefty/lefty.psp \
    graphviz/release/lib/lefty/slides.lefty \
    graphviz/release/lib/lefty/tree.lefty \
    graphviz/release/lib/pkgconfig/libcdt.pc \
    graphviz/release/lib/pkgconfig/libcgraph.pc \
    graphviz/release/lib/pkgconfig/libgraph.pc \
    graphviz/release/lib/pkgconfig/libgvc.pc \
    graphviz/release/lib/pkgconfig/libpathplan.pc \
    graphviz/release/lib/release/dll/dummyfile.txt \
    graphviz/release/lib/release/lib/dummyfile.txt \
    graphviz/release/pango/pango.aliases \
    graphviz/release/pango/pango.modules \
    graphviz/release/share/graphviz/doc/addingLayout.txt \
    graphviz/release/share/graphviz/doc/cpl1.0.txt \
    graphviz/release/share/graphviz/doc/Dot.ref \
    graphviz/release/share/graphviz/doc/fontfaq.txt \
    graphviz/release/share/graphviz/doc/latex_suggestions.txt \
    graphviz/release/share/graphviz/doc/NEWS \
    graphviz/release/share/graphviz/gvedit/attributes.txt \
    graphviz/release/share/graphviz/lefty/box.lefty \
    graphviz/release/share/graphviz/lefty/def.lefty \
    graphviz/release/share/graphviz/lefty/dotty.lefty \
    graphviz/release/share/graphviz/lefty/dotty_draw.lefty \
    graphviz/release/share/graphviz/lefty/dotty_edit.lefty \
    graphviz/release/share/graphviz/lefty/dotty_layout.lefty \
    graphviz/release/share/graphviz/lefty/dotty_ui.lefty \
    graphviz/release/share/graphviz/lefty/fractal.lefty \
    graphviz/release/share/graphviz/lefty/fractal2.lefty \
    graphviz/release/share/graphviz/lefty/lefty.psp \
    graphviz/release/share/graphviz/lefty/slides.lefty \
    graphviz/release/share/graphviz/lefty/tree.lefty \
    graphviz/release/share/graphviz/smyrna/attrs.txt \
    graphviz/release/share/graphviz/smyrna/mouse_actions.txt \
    graphviz/release/share/man/man1/acyclic.1 \
    graphviz/release/share/man/man1/bcomps.1 \
    graphviz/release/share/man/man1/ccomps.1 \
    graphviz/release/share/man/man1/circo.1 \
    graphviz/release/share/man/man1/dijkstra.1 \
    graphviz/release/share/man/man1/dot.1 \
    graphviz/release/share/man/man1/dotty.1 \
    graphviz/release/share/man/man1/fdp.1 \
    graphviz/release/share/man/man1/gc.1 \
    graphviz/release/share/man/man1/gv2gxl.1 \
    graphviz/release/share/man/man1/gvcolor.1 \
    graphviz/release/share/man/man1/gvgen.1 \
    graphviz/release/share/man/man1/gvpack.1 \
    graphviz/release/share/man/man1/gvpr.1 \
    graphviz/release/share/man/man1/gxl2gv.1 \
    graphviz/release/share/man/man1/lefty.1 \
    graphviz/release/share/man/man1/lneato.1 \
    graphviz/release/share/man/man1/mm2gv.1 \
    graphviz/release/share/man/man1/neato.1 \
    graphviz/release/share/man/man1/nop.1 \
    graphviz/release/share/man/man1/osage.1 \
    graphviz/release/share/man/man1/sccmap.1 \
    graphviz/release/share/man/man1/tred.1 \
    graphviz/release/share/man/man1/twopi.1 \
    graphviz/release/share/man/man1/unflatten.1 \
    graphviz/share/graphviz/doc/addingLayout.txt \
    graphviz/share/graphviz/doc/cpl1.0.txt \
    graphviz/share/graphviz/doc/Dot.ref \
    graphviz/share/graphviz/doc/fontfaq.txt \
    graphviz/share/graphviz/doc/latex_suggestions.txt \
    graphviz/share/graphviz/doc/NEWS \
    graphviz/share/graphviz/gvedit/attributes.txt \
    graphviz/share/graphviz/lefty/box.lefty \
    graphviz/share/graphviz/lefty/def.lefty \
    graphviz/share/graphviz/lefty/dotty.lefty \
    graphviz/share/graphviz/lefty/dotty_draw.lefty \
    graphviz/share/graphviz/lefty/dotty_edit.lefty \
    graphviz/share/graphviz/lefty/dotty_layout.lefty \
    graphviz/share/graphviz/lefty/dotty_ui.lefty \
    graphviz/share/graphviz/lefty/fractal.lefty \
    graphviz/share/graphviz/lefty/fractal2.lefty \
    graphviz/share/graphviz/lefty/lefty.psp \
    graphviz/share/graphviz/lefty/slides.lefty \
    graphviz/share/graphviz/lefty/tree.lefty \
    graphviz/share/graphviz/smyrna/attrs.txt \
    graphviz/share/graphviz/smyrna/mouse_actions.txt \
    graphviz/share/man/man1/acyclic.1 \
    graphviz/share/man/man1/bcomps.1 \
    graphviz/share/man/man1/ccomps.1 \
    graphviz/share/man/man1/circo.1 \
    graphviz/share/man/man1/dijkstra.1 \
    graphviz/share/man/man1/dot.1 \
    graphviz/share/man/man1/dotty.1 \
    graphviz/share/man/man1/fdp.1 \
    graphviz/share/man/man1/gc.1 \
    graphviz/share/man/man1/gv2gxl.1 \
    graphviz/share/man/man1/gvcolor.1 \
    graphviz/share/man/man1/gvgen.1 \
    graphviz/share/man/man1/gvpack.1 \
    graphviz/share/man/man1/gvpr.1 \
    graphviz/share/man/man1/gxl2gv.1 \
    graphviz/share/man/man1/lefty.1 \
    graphviz/share/man/man1/lneato.1 \
    graphviz/share/man/man1/mm2gv.1 \
    graphviz/share/man/man1/neato.1 \
    graphviz/share/man/man1/nop.1 \
    graphviz/share/man/man1/osage.1 \
    graphviz/share/man/man1/sccmap.1 \
    graphviz/share/man/man1/tred.1 \
    graphviz/share/man/man1/twopi.1 \
    graphviz/share/man/man1/unflatten.1 \
    graphviz/release/share/man/man1/prune.1 \
    graphviz/release/share/man/man7/graphviz.7 \
    graphviz/share/man/man1/prune.1 \
    graphviz/share/man/man7/graphviz.7 \
    graphviz/release/share/graphviz/doc/html/info/html2.dot \
    graphviz/release/share/graphviz/doc/html/info/html3.dot \
    graphviz/release/share/graphviz/doc/html/info/html4.dot \
    graphviz/release/share/graphviz/examples/4elt.gv \
    graphviz/release/share/graphviz/examples/world.gv \
    graphviz/release/share/graphviz/graphs/directed/abstract.gv \
    graphviz/release/share/graphviz/graphs/directed/alf.gv \
    graphviz/release/share/graphviz/graphs/directed/arrows.gv \
    graphviz/release/share/graphviz/graphs/directed/awilliams.gv \
    graphviz/release/share/graphviz/graphs/directed/clust.gv \
    graphviz/release/share/graphviz/graphs/directed/clust1.gv \
    graphviz/release/share/graphviz/graphs/directed/clust2.gv \
    graphviz/release/share/graphviz/graphs/directed/clust3.gv \
    graphviz/release/share/graphviz/graphs/directed/clust4.gv \
    graphviz/release/share/graphviz/graphs/directed/clust5.gv \
    graphviz/release/share/graphviz/graphs/directed/crazy.gv \
    graphviz/release/share/graphviz/graphs/directed/ctext.gv \
    graphviz/release/share/graphviz/graphs/directed/dfa.gv \
    graphviz/release/share/graphviz/graphs/directed/fig6.gv \
    graphviz/release/share/graphviz/graphs/directed/fsm.gv \
    graphviz/release/share/graphviz/graphs/directed/grammar.gv \
    graphviz/release/share/graphviz/graphs/directed/hashtable.gv \
    graphviz/release/share/graphviz/graphs/directed/honda-tokoro.gv \
    graphviz/release/share/graphviz/graphs/directed/jcctree.gv \
    graphviz/release/share/graphviz/graphs/directed/jsort.gv \
    graphviz/release/share/graphviz/graphs/directed/KW91.gv \
    graphviz/release/share/graphviz/graphs/directed/Latin1.gv \
    graphviz/release/share/graphviz/graphs/directed/ldbxtried.gv \
    graphviz/release/share/graphviz/graphs/directed/longflat.gv \
    graphviz/release/share/graphviz/graphs/directed/mike.gv \
    graphviz/release/share/graphviz/graphs/directed/NaN.gv \
    graphviz/release/share/graphviz/graphs/directed/nhg.gv \
    graphviz/release/share/graphviz/graphs/directed/oldarrows.gv \
    graphviz/release/share/graphviz/graphs/directed/pgram.gv \
    graphviz/release/share/graphviz/graphs/directed/pm2way.gv \
    graphviz/release/share/graphviz/graphs/directed/pmpipe.gv \
    graphviz/release/share/graphviz/graphs/directed/polypoly.gv \
    graphviz/release/share/graphviz/graphs/directed/proc3d.gv \
    graphviz/release/share/graphviz/graphs/directed/psfonttest.gv \
    graphviz/release/share/graphviz/graphs/directed/record2.gv \
    graphviz/release/share/graphviz/graphs/directed/records.gv \
    graphviz/release/share/graphviz/graphs/directed/rowe.gv \
    graphviz/release/share/graphviz/graphs/directed/russian.gv \
    graphviz/release/share/graphviz/graphs/directed/sdh.gv \
    graphviz/release/share/graphviz/graphs/directed/shells.gv \
    graphviz/release/share/graphviz/graphs/directed/states.gv \
    graphviz/release/share/graphviz/graphs/directed/structs.gv \
    graphviz/release/share/graphviz/graphs/directed/switch.gv \
    graphviz/release/share/graphviz/graphs/directed/table.gv \
    graphviz/release/share/graphviz/graphs/directed/train11.gv \
    graphviz/release/share/graphviz/graphs/directed/trapeziumlr.gv \
    graphviz/release/share/graphviz/graphs/directed/tree.gv \
    graphviz/release/share/graphviz/graphs/directed/triedds.gv \
    graphviz/release/share/graphviz/graphs/directed/try.gv \
    graphviz/release/share/graphviz/graphs/directed/unix.gv \
    graphviz/release/share/graphviz/graphs/directed/unix2.gv \
    graphviz/release/share/graphviz/graphs/directed/viewfile.gv \
    graphviz/release/share/graphviz/graphs/directed/world.gv \
    graphviz/release/share/graphviz/graphs/smyrna/4elt.dot \
    graphviz/release/share/graphviz/graphs/smyrna/world.dot \
    graphviz/release/share/graphviz/graphs/undirected/ER.gv \
    graphviz/release/share/graphviz/graphs/undirected/Heawood.gv \
    graphviz/release/share/graphviz/graphs/undirected/ngk10_4.gv \
    graphviz/release/share/graphviz/graphs/undirected/Petersen.gv \
    graphviz/release/share/graphviz/graphs/undirected/process.gv \
    graphviz/release/share/graphviz/smyrna/attr_widgets.dot \
    graphviz/release/share/graphviz/smyrna/template.dot \
    graphviz/share/graphviz/doc/html/info/html2.dot \
    graphviz/share/graphviz/doc/html/info/html3.dot \
    graphviz/share/graphviz/doc/html/info/html4.dot \
    graphviz/share/graphviz/examples/4elt.gv \
    graphviz/share/graphviz/examples/world.gv \
    graphviz/share/graphviz/graphs/directed/abstract.gv \
    graphviz/share/graphviz/graphs/directed/alf.gv \
    graphviz/share/graphviz/graphs/directed/arrows.gv \
    graphviz/share/graphviz/graphs/directed/awilliams.gv \
    graphviz/share/graphviz/graphs/directed/clust.gv \
    graphviz/share/graphviz/graphs/directed/clust1.gv \
    graphviz/share/graphviz/graphs/directed/clust2.gv \
    graphviz/share/graphviz/graphs/directed/clust3.gv \
    graphviz/share/graphviz/graphs/directed/clust4.gv \
    graphviz/share/graphviz/graphs/directed/clust5.gv \
    graphviz/share/graphviz/graphs/directed/crazy.gv \
    graphviz/share/graphviz/graphs/directed/ctext.gv \
    graphviz/share/graphviz/graphs/directed/dfa.gv \
    graphviz/share/graphviz/graphs/directed/fig6.gv \
    graphviz/share/graphviz/graphs/directed/fsm.gv \
    graphviz/share/graphviz/graphs/directed/grammar.gv \
    graphviz/share/graphviz/graphs/directed/hashtable.gv \
    graphviz/share/graphviz/graphs/directed/honda-tokoro.gv \
    graphviz/share/graphviz/graphs/directed/jcctree.gv \
    graphviz/share/graphviz/graphs/directed/jsort.gv \
    graphviz/share/graphviz/graphs/directed/KW91.gv \
    graphviz/share/graphviz/graphs/directed/Latin1.gv \
    graphviz/share/graphviz/graphs/directed/ldbxtried.gv \
    graphviz/share/graphviz/graphs/directed/longflat.gv \
    graphviz/share/graphviz/graphs/directed/mike.gv \
    graphviz/share/graphviz/graphs/directed/NaN.gv \
    graphviz/share/graphviz/graphs/directed/nhg.gv \
    graphviz/share/graphviz/graphs/directed/oldarrows.gv \
    graphviz/share/graphviz/graphs/directed/pgram.gv \
    graphviz/share/graphviz/graphs/directed/pm2way.gv \
    graphviz/share/graphviz/graphs/directed/pmpipe.gv \
    graphviz/share/graphviz/graphs/directed/polypoly.gv \
    graphviz/share/graphviz/graphs/directed/proc3d.gv \
    graphviz/share/graphviz/graphs/directed/psfonttest.gv \
    graphviz/share/graphviz/graphs/directed/record2.gv \
    graphviz/share/graphviz/graphs/directed/records.gv \
    graphviz/share/graphviz/graphs/directed/rowe.gv \
    graphviz/share/graphviz/graphs/directed/russian.gv \
    graphviz/share/graphviz/graphs/directed/sdh.gv \
    graphviz/share/graphviz/graphs/directed/shells.gv \
    graphviz/share/graphviz/graphs/directed/states.gv \
    graphviz/share/graphviz/graphs/directed/structs.gv \
    graphviz/share/graphviz/graphs/directed/switch.gv \
    graphviz/share/graphviz/graphs/directed/table.gv \
    graphviz/share/graphviz/graphs/directed/train11.gv \
    graphviz/share/graphviz/graphs/directed/trapeziumlr.gv \
    graphviz/share/graphviz/graphs/directed/tree.gv \
    graphviz/share/graphviz/graphs/directed/triedds.gv \
    graphviz/share/graphviz/graphs/directed/try.gv \
    graphviz/share/graphviz/graphs/directed/unix.gv \
    graphviz/share/graphviz/graphs/directed/unix2.gv \
    graphviz/share/graphviz/graphs/directed/viewfile.gv \
    graphviz/share/graphviz/graphs/directed/world.gv \
    graphviz/share/graphviz/graphs/smyrna/4elt.dot \
    graphviz/share/graphviz/graphs/smyrna/world.dot \
    graphviz/share/graphviz/graphs/undirected/ER.gv \
    graphviz/share/graphviz/graphs/undirected/Heawood.gv \
    graphviz/share/graphviz/graphs/undirected/ngk10_4.gv \
    graphviz/share/graphviz/graphs/undirected/Petersen.gv \
    graphviz/share/graphviz/graphs/undirected/process.gv \
    graphviz/share/graphviz/smyrna/attr_widgets.dot \
    graphviz/share/graphviz/smyrna/template.dot \
    graphviz/release/share/graphviz/doc/AUTHORS \
    graphviz/share/graphviz/doc/AUTHORS \
    graphviz/release/share/graphviz/doc/ChangeLog \
    graphviz/share/graphviz/doc/ChangeLog \
    graphviz/release/share/graphviz/doc/COPYING \
    graphviz/share/graphviz/doc/COPYING \
    graphviz/etc/fonts/conf.avail/README \
    graphviz/fonts/conf.avail/README \
    graphviz/release/etc/fonts/conf.avail/README \
    graphviz/release/fonts/conf.avail/README
